name: rumsan-mcp-servers

services:
  banking-mcp:
    build: .
    image: rumsan/banking-mcp
    container_name: banking-mcp
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - MCP_AUTH_TOKEN=${MCP_AUTH_TOKEN}
